spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/flyoptimistic/spring-cloud-config.git # 配置git仓库的地址
          search-paths: config-repo # git仓库地址下的相对地址，可以配置多个，用,分割。
#  profiles:
#    active: native

server:
  port: 12000

