server:
  port: 7001

eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer2:7002/eureka/,http://peer3:7003/eureka/

spring:
  application:
    name: eureka-server


