server:
  port: 7003

eureka:
  instance:
    hostname: peer3
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/

spring:
  application:
    name: eureka-server


